--Please be aware that table(s) below may have triggers on them  
--Verification  
SELECT sys_context('USERENV','SERVICE_NAME') "DATABASE NAME", SYSDATE "AS OF DATE STATE" FROM DUAL;

SELECT 'EOAWCRTA' "TABLE NAME",REC.EOAWCRTA_ID,REC.DESCR,REC.EOAWCRTA_SOURCE,REC.QRYNAME,REC.SQLID,REC.PACKAGEROOT,REC.APPCLASS_PATH,REC.APP_CLASS,REC.EOAWCRITERIA_FLG FROM PS_EOAWCRTA REC WHERE EOAWCRTA_ID LIKE '%Thailand2019-01-01%' ORDER BY 1,2;

SELECT 'EOAWCRTA_REC' "TABLE NAME",REC.EOAWCRTA_ID,REC.SEQ_NBR,REC.RECNAME,REC.FIELDNAME,REC.AMT_RECNAME,REC.AMT_FLDNAME,REC.EOAWCRITERIA_FLG,REC.EOAWAMOUNT_SW,REC.EOAWCRTA_OP_NUM,REC.AMOUNT_1,REC.AMOUNT_2,REC.CURRENCY_CD,REC.CUR_RT_TYPE,REC.RECNAME_CUR,REC.FIELDNAME_CUR,REC.DESCR254_MIXED FROM PS_EOAWCRTA_REC REC WHERE EOAWCRTA_ID LIKE '%Thailand2019-01-01%' ORDER BY 1,2,3,4,5,6,7;

SELECT 'EOAWCRTA_VAL' "TABLE NAME",REC.EOAWCRTA_ID,REC.SEQ_NBR,REC.RECNAME,REC.FIELDNAME,REC.EOAWCRTA_VAL1,REC.EOAWCRTA_OPERATOR,REC.EOAWCRTA_VAL2,REC.EOAWCRTA_VAL3 FROM PS_EOAWCRTA_VAL REC WHERE EOAWCRTA_ID LIKE '%Thailand2019-01-01%' ORDER BY 1,2,3,4,5,6;

SELECT 'EOAW_PATH' "TABLE NAME",REC.EOAWPRCS_ID,REC.EOAWDEFN_ID,REC.EFFDT,REC.EOAWSTAGE_NBR,REC.EOAWPATH_ID,REC.EOAWSTEP_SOURCE,REC.EOAWNUMBER_HOURS,REC.EOAWNUMBER_DAYS,REC.EOAWESCALATN_OPTN,REC.DESCR,REC.EOAWCRTA_ID,REC.EOAWSKIP_PRIOR,REC.EOAWAUTH_SW,REC.EOAWFIRST_STEP_SW,REC.EOAWREQUIREFIRST,REC.EOAWSKIP_UNAUTHED,REC.DESCRLONG,REC.EOAWNOTIFY_ADMIN FROM PS_EOAW_PATH REC WHERE EFFDT=TO_DATE('01/01/2019','DD/MM/YYYY') AND EOAWDEFN_ID = 'Voucher Approval Thailand' AND EOAWPRCS_ID = 'VoucherApproval' ORDER BY 1,2,3,4,5,6;

SELECT 'EOAW_PRCS' "TABLE NAME",REC.EOAWPRCS_ID,REC.EOAWDEFN_ID,REC.EFFDT,REC.EFF_STATUS,REC.DESCR,REC.EOAWADMIN_ROLENAME,REC.EOAWACT_LINE_LEVEL,REC.EOAWAUTO_APPROVE,REC.EOAWFIELD_LIST_ID,REC.EOAWCRTA_ID,REC.EOAWDEFN_CRTA_ID,REC.EOAW_REQSTR_SW,REC.EOAW_INCL_REQSTR,REC.EOAWDEFN_DEFAULT,REC.EOAWDEFN_PRIORITY,REC.EOAW_CALENDAR FROM PS_EOAW_PRCS REC WHERE EFFDT=TO_DATE('01/01/2019','DD/MM/YYYY') AND EOAWDEFN_ID = 'Voucher Approval Thailand' AND EOAWPRCS_ID = 'VoucherApproval' ORDER BY 1,2,3,4;

SELECT 'EOAW_STAGE' "TABLE NAME",REC.EOAWPRCS_ID,REC.EOAWDEFN_ID,REC.EFFDT,REC.EOAWSTAGE_NBR,REC.DESCR,REC.SEQ_NBR,REC.EOAWLEVEL FROM PS_EOAW_STAGE REC WHERE EOAWDEFN_ID = 'Voucher Approval Thailand' AND EOAWPRCS_ID = 'VoucherApproval' AND EFFDT=TO_DATE('01/01/2019','DD/MM/YYYY') ORDER BY 1,2,3,4,5;

SELECT 'EOAW_STEP' "TABLE NAME",REC.EOAWPRCS_ID,REC.EOAWDEFN_ID,REC.EFFDT,REC.EOAWSTAGE_NBR,REC.EOAWPATH_ID,REC.EOAWSTEP_NBR,REC.SEQ_NBR,REC.EOAWAPPROVER_LIST,REC.EOAWAPPROVER_SW,REC.EOAWMIN_APPROVERS,REC.EOAWROLENAME,REC.EOAWSELF_APPROVAL,REC.EOAWSELF_CRTA_ID,REC.EOAWREVIEWER_LIST,REC.EOAW_REQSTR_SW,REC.EOAW_FILTER_REQ,REC.DESCR,REC.EOAWCRTA_ID,REC.EOAW_EXTERN_FLAG FROM PS_EOAW_STEP REC WHERE EFFDT=TO_DATE('01/01/2019','DD/MM/YYYY') AND EOAWDEFN_ID = 'Voucher Approval Thailand' AND EOAWPRCS_ID = 'VoucherApproval' ORDER BY 1,2,3,4,5,6,7;

SELECT 'EOAW_TIMEOUT' "TABLE NAME",REC.EOAWPRCS_ID,REC.EOAWDEFN_ID,REC.EFFDT,REC.EOAWSTAGE_NBR,REC.EOAWPATH_ID,REC.SEQ_NBR,REC.EOAWESCALATN_OPTN,REC.EOAWNUMBER_HOURS,REC.EOAWNUMBER_DAYS,REC.EOAWREASSIGNOPRID,REC.EOAWUSER_LIST_ID,REC.TIMEOUTMINUTES,REC.EOAW_TIMEOUTMINUTE,REC.EOAWACTUAL_APPR FROM PS_EOAW_TIMEOUT REC WHERE EFFDT=TO_DATE('01/01/2019','DD/MM/YYYY') AND EOAWDEFN_ID = 'Voucher Approval Thailand' AND EOAWPRCS_ID = 'VoucherApproval' ORDER BY 1,2,3,4,5,6,7;

SELECT 'WL_TEMPLATE_GEN' "TABLE NAME",REC.WL_TEMPLATE_ID, REC.DESCR,REC.WL_PRIORITY,REC.WL_SENDER,REC.EMAILID,REC.WL_SUBJECT,REC.WL_INSTR_TXT,REC.WL_RESPONSE_TXT,REC.WL_ADDED_OPRID,REC.WL_ADDED_DTTM,REC.WL_LASTMANT_OPRID,REC.WL_LASTMANT_DTTM,REC.WL_MSG_TXT FROM PS_WL_TEMPLATE_GEN REC WHERE WL_TEMPLATE_ID LIKE 'Voucher%THA' ORDER BY 1,2,3,4,5;

SELECT 'WL_TEMPL_GEN_TK' "TABLE NAME", REC.WL_TEMPLATE_ID,REC.SEQNO,REC.WL_TOKENID,REC.DESCR,REC.WL_ADDED_OPRID,REC.WL_ADDED_DTTM,REC.WL_LASTMANT_OPRID,REC.WL_LASTMANT_DTTM
FROM PS_WL_TEMPL_GEN_TK REC WHERE WL_TEMPLATE_ID LIKE 'Voucher%THA' ORDER BY 1,2;

SELECT 'EOAW_NOTIFYDEF' "TABLE_NAME", REC.EOAWPRCS_ID,REC.EOAWDEFN_ID, REC.EFFDT,REC.EOAWLEVEL, REC.EOAWEVENT, REC.MENUNAME,REC.EOAWAPPR_COMPONENT,REC.PAGE_NAME,REC.EOAWMENU_ACTION,REC.WL_TEMPLATE_ID,REC.SQLID,REC.RECNAME FROM PS_EOAW_NOTIFYDEF REC WHERE EOAWPRCS_ID = 'VoucherApproval' AND EOAWDEFN_ID = 'Voucher Approval Thailand' AND EFFDT = TO_DATE('01/01/2019','DD/MM/YYYY') ORDER BY 1,2,3,4,5;

SELECT 'EOAW_NOT_USRDEF' "TABLE_NAME",REC.EOAWPRCS_ID,REC.EOAWDEFN_ID, REC.EFFDT,REC.EOAWLEVEL, REC.EOAWEVENT,REC.EOAWPARTICIPANT, REC.EOAWUSER_LIST_ID,REC.EOAWCHANNEL,REC.WL_TEMPLATE_ID,REC.MENUNAME,REC.EOAWAPPR_COMPONENT,REC.PAGE_NAME,REC.EOAWMENU_ACTION,REC.SQLID,REC.WL_PRIORITY,REC.EOAWNUMBER_HOURS,REC.EOAWNOTIFY_INTERVL,REC.EOAWMAX_SEND,REC.EOAW_EMAIL,REC.EOAW_WORKLIST,REC.EOAW_PUSH,REC.EOAW_USER,REC.EOAW_MSGSET,REC.EOAW_MSGNBR,REC.EOAW_SQLID,REC.EOAW_PUSH_EXURL FROM PS_EOAW_NOT_USRDEF REC WHERE EOAWPRCS_ID = 'VoucherApproval' AND EOAWDEFN_ID = 'Voucher Approval Thailand' AND EFFDT = TO_DATE('01/01/2019','DD/MM/YYYY') ORDER BY 1,2,3,4,5,6,7;